### PR TITLE
Add routes and component files.

### PR DESCRIPTION
**Pull request by michalzagrodzki**
1. Add named routes to router.
2. Add components for routes as empty files.

### CODE REVIEW

**Comment by mchandleraz** [comment]
Hey @michalzagrodzki, the code looks great but I'm not sure I wanna merge this one just yet. I'd like to see some tests.

I appreciate the help and would love to get your changes merged. Do you have any experience with unit testing? I think if we had some tests around this PR it'd be good to go. If you need some help, let me know- I'm happy to share what I know.

**Comment by michalzagrodzki** [comment]
@mchandleraz Don't have any experience with unit-testing.

**Comment by mchandleraz** [comment]
No worries @michalzagrodzki ! I'll take a look at Vue Router in a few hours and we can talk about adding some tests via Gitter. This should be pretty easy to test.

**Comment by mchandleraz** [comment]
After taking a look at this, I realized there's really nothing to test since we can trust vue-router.

**Pull request merged**
