### PR TITLE
Add redirection to home view if user types wrong url.

### PR DESCRIPTION
**Pull request by michalzagrodzki**
Add path in router for redirecting invalid routes to home view.
Used naming convention for routes.

Similar example: https://github.com/vuejs/vue-router/blob/dev/examples/redirect/app.js

### CODE REVIEW

**Comment by StevenYuysy** [comment]
Why not just display 404 page instead of redirecting to home page?

**Comment by michalzagrodzki** [comment]
@StevenYuysy I followed the instructions provided in FRONTEND_INSTRUCTIONS file in realworld-starter-kit repo. 
In those instructions there is no mentioning about the 404 page, so I assumed that there will be redirection in case of invalid url.

**Comment by StevenYuysy** [comment]
Well, since there is no mentioning about the 404 page, I open an issue about this question.
https://github.com/gothinkster/realworld-starter-kit/issues/9

**Review by mchandleraz — APPROVED** [review]
Thanks Michal!

**Pull request merged**
